version: "3.8"

services:
  postgres-db:
    container_name: mukbang_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: yin
      POSTGRES_PASSWORD: yang
      POSTGRES_DB: mukbang_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5424:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
    driver: local
